# Generated by Django 4.2.6 on 2026-07-22 16:48

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rental.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(verbose_name='帳單月份')),
                ('due_date', models.DateField(verbose_name='付款期限')),
                ('status', models.CharField(choices=[('draft', '待租客填寫'), ('submitted', '待管理者確認'), ('confirmed', '待租客付款'), ('payment_submitted', '待確認收款'), ('paid', '已結案'), ('void', '已作廢')], default='draft', max_length=24, verbose_name='帳單狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交時間')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='帳單確認時間')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='結案時間')),
            ],
            options={
                'verbose_name': '帳單',
                'verbose_name_plural': '帳單',
                'ordering': ['-period', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='起租日')),
                ('end_date', models.DateField(verbose_name='到期日')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='每月租金')),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='押金')),
                ('due_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='每月應繳日')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '有效'), ('ended', '已結束'), ('terminated', '提前終止')], default='draft', max_length=16, verbose_name='租約狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '租約',
                'verbose_name_plural': '租約',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='物件名稱')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('status', models.CharField(choices=[('active', '使用中'), ('inactive', '停用')], default='active', max_length=16, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_properties', to=settings.AUTH_USER_MODEL, verbose_name='房東')),
            ],
            options={
                'verbose_name': '物件',
                'verbose_name_plural': '物件',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(blank=True, max_length=30, verbose_name='樓層')),
                ('number', models.CharField(max_length=40, verbose_name='房號')),
                ('room_type', models.CharField(blank=True, max_length=80, verbose_name='房型')),
                ('area_ping', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='坪數')),
                ('status', models.CharField(choices=[('available', '可出租'), ('occupied', '已出租'), ('maintenance', '維修中'), ('inactive', '停用')], default='available', max_length=16, verbose_name='出租狀態')),
                ('notes', models.TextField(blank=True, verbose_name='現況說明')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rental.property', verbose_name='物件')),
            ],
            options={
                'verbose_name': '房間',
                'verbose_name_plural': '房間',
                'ordering': ['property__name', 'floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='UnitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=rental.models.rental_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), rental.models.validate_upload_size], verbose_name='現況照片')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='說明')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rental.unit', verbose_name='房間')),
            ],
            options={
                'verbose_name': '房間現況照片',
                'verbose_name_plural': '房間現況照片',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='附屬設備')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rental.unit', verbose_name='房間')),
            ],
            options={
                'verbose_name': '房間設備',
                'verbose_name_plural': '房間設備',
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='聯絡電話')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=80, verbose_name='緊急聯絡人')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, verbose_name='緊急聯絡電話')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '租客資料',
                'verbose_name_plural': '租客資料',
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_name', models.CharField(max_length=80, verbose_name='受邀租客姓名')),
                ('invited_email', models.EmailField(blank=True, max_length=254, verbose_name='受邀租客 Email')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='邀請識別碼')),
                ('expires_at', models.DateTimeField(verbose_name='到期時間')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接受時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='接受會員')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tenant_invitations', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rental.lease', verbose_name='租約')),
            ],
            options={
                'verbose_name': '租客邀請',
                'verbose_name_plural': '租客邀請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', '物件管理者')], default='manager', max_length=16, verbose_name='角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='rental.property', verbose_name='物件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '物件管理權限',
                'verbose_name_plural': '物件管理權限',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='報修主旨')),
                ('description', models.TextField(verbose_name='問題說明')),
                ('status', models.CharField(choices=[('open', '待處理'), ('in_progress', '處理中'), ('completed', '已完成'), ('closed', '已關閉')], default='open', max_length=16, verbose_name='進度')),
                ('completion_note', models.TextField(blank=True, verbose_name='完成紀錄')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='處理人員')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='提報人')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='rental.lease', verbose_name='租約')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='rental.unit', verbose_name='房間')),
            ],
            options={
                'verbose_name': '維修報修',
                'verbose_name_plural': '維修報修',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=rental.models.rental_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), rental.models.validate_upload_size], verbose_name='照片或附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rental.maintenancerequest', verbose_name='報修單')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '報修附件',
                'verbose_name_plural': '報修附件',
            },
        ),
        migrations.CreateModel(
            name='LeaseTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', '待接受邀請'), ('active', '入住中'), ('moved_out', '已退租')], default='invited', max_length=16, verbose_name='入住狀態')),
                ('move_in_date', models.DateField(blank=True, null=True, verbose_name='入住日')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='退租日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_tenants', to='rental.lease', verbose_name='租約')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_tenants', to='rental.tenantprofile', verbose_name='租客')),
            ],
            options={
                'verbose_name': '租約租客',
                'verbose_name_plural': '租約租客',
            },
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='文件名稱')),
                ('file', models.FileField(upload_to=rental.models.rental_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), rental.models.validate_upload_size], verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rental.lease', verbose_name='租約')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '租約附件',
                'verbose_name_plural': '租約附件',
            },
        ),
        migrations.CreateModel(
            name='LeaseCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='項目名稱')),
                ('charge_type', models.CharField(choices=[('water', '水費'), ('gas', '瓦斯費'), ('management', '管理費'), ('other', '其他')], default='other', max_length=16, verbose_name='類型')),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='預設金額')),
                ('tenant_editable', models.BooleanField(default=True, verbose_name='租客可編輯')),
                ('enabled', models.BooleanField(default=True, verbose_name='啟用')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_charges', to='rental.lease', verbose_name='租約')),
            ],
            options={
                'verbose_name': '租約固定費用',
                'verbose_name_plural': '租約固定費用',
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='rental.unit', verbose_name='房間'),
        ),
        migrations.CreateModel(
            name='ElectricityRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='費率名稱')),
                ('start_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='起始月份')),
                ('end_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='結束月份')),
                ('rate_per_kwh', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='每度電價')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_rates', to='rental.lease', verbose_name='租約')),
            ],
            options={
                'verbose_name': '季節電價',
                'verbose_name_plural': '季節電價',
            },
        ),
        migrations.CreateModel(
            name='BillSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64, verbose_name='流程事件')),
                ('payload', models.JSONField(default=dict, verbose_name='帳單快照')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作會員')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='rental.bill', verbose_name='帳單')),
            ],
            options={
                'verbose_name': '帳單快照',
                'verbose_name_plural': '帳單快照',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('transfer', '銀行匯款'), ('cash', '現金支付')], max_length=16, verbose_name='付款方式')),
                ('receipt', models.FileField(blank=True, upload_to=rental.models.rental_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), rental.models.validate_upload_size], verbose_name='匯款憑證')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='付款提交時間')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='收款確認時間')),
                ('note', models.TextField(blank=True, verbose_name='付款備註')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rental.bill', verbose_name='帳單')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_rental_payments', to=settings.AUTH_USER_MODEL, verbose_name='收款確認者')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_rental_payments', to=settings.AUTH_USER_MODEL, verbose_name='付款人')),
            ],
            options={
                'verbose_name': '帳單付款',
                'verbose_name_plural': '帳單付款',
            },
        ),
        migrations.CreateModel(
            name='BillMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='抄表日期')),
                ('previous_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='前次度數')),
                ('current_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='本次度數')),
                ('photo', models.FileField(blank=True, upload_to=rental.models.rental_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'pdf']), rental.models.validate_upload_size], verbose_name='電表照片')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meter_reading', to='rental.bill', verbose_name='帳單')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='填寫者')),
            ],
            options={
                'verbose_name': '電表抄表',
                'verbose_name_plural': '電表抄表',
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('rent', '租金'), ('electricity', '電費'), ('water', '水費'), ('gas', '瓦斯費'), ('management', '管理費'), ('other', '其他')], default='other', max_length=16, verbose_name='項目類型')),
                ('name', models.CharField(max_length=100, verbose_name='項目名稱')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額')),
                ('tenant_editable', models.BooleanField(default=False, verbose_name='租客可編輯')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.bill', verbose_name='帳單')),
            ],
            options={
                'verbose_name': '帳單項目',
                'verbose_name_plural': '帳單項目',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='rental.lease', verbose_name='租約'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='公告標題')),
                ('content', models.TextField(verbose_name='公告內容')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='發布時間')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='下架時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_announcements', to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='rental.property', verbose_name='指定物件')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='unitamenity',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_unit_amenity'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('property', 'number'), name='unique_unit_number_per_property'),
        ),
        migrations.AddConstraint(
            model_name='propertymembership',
            constraint=models.UniqueConstraint(fields=('property', 'user'), name='unique_property_membership'),
        ),
        migrations.AddConstraint(
            model_name='leasetenant',
            constraint=models.UniqueConstraint(fields=('lease', 'tenant'), name='unique_lease_tenant'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('lease', 'period'), name='unique_bill_per_lease_period'),
        ),
    ]
