# Generated by Django 4.2.6 on 2026-07-23 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import rental.models


def backfill_billing_access_start_dates(apps, schema_editor):
    Lease = apps.get_model('rental', 'Lease')
    LeaseTenant = apps.get_model('rental', 'LeaseTenant')
    TenantInvitation = apps.get_model('rental', 'TenantInvitation')
    lease_start_dates = dict(Lease.objects.values_list('id', 'start_date'))

    for lease_tenant in LeaseTenant.objects.filter(billing_access_start_date__isnull=True).iterator():
        lease_tenant.billing_access_start_date = lease_tenant.move_in_date or lease_start_dates[lease_tenant.lease_id]
        lease_tenant.save(update_fields=['billing_access_start_date'])

    for invitation in TenantInvitation.objects.filter(billing_access_start_date__isnull=True).iterator():
        invitation.billing_access_start_date = lease_start_dates[invitation.lease_id]
        invitation.save(update_fields=['billing_access_start_date'])


def reverse_backfill_billing_access_start_dates(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leasetenant',
            name='billing_access_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='帳務權限生效日'),
        ),
        migrations.AddField(
            model_name='tenantinvitation',
            name='billing_access_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='帳務權限生效日'),
        ),
        migrations.RunPython(backfill_billing_access_start_dates, reverse_backfill_billing_access_start_dates),
        migrations.AlterField(
            model_name='billmeterreading',
            name='photo',
            field=models.FileField(blank=True, upload_to=rental.models.rental_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), rental.models.validate_upload_size], verbose_name='電表照片'),
        ),
        migrations.AlterField(
            model_name='unitphoto',
            name='image',
            field=models.FileField(upload_to=rental.models.rental_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), rental.models.validate_upload_size], verbose_name='現況照片'),
        ),
        migrations.CreateModel(
            name='BillTenantPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='授權到期日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='授權時間')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_permissions', to='rental.bill', verbose_name='帳單')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_bill_tenant_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授權管理者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_permissions', to='rental.leasetenant', verbose_name='租客租約關係')),
            ],
            options={
                'verbose_name': '帳單租客補填授權',
                'verbose_name_plural': '帳單租客補填授權',
            },
        ),
        migrations.AddConstraint(
            model_name='billtenantpermission',
            constraint=models.UniqueConstraint(fields=('bill', 'tenant'), name='unique_bill_tenant_permission'),
        ),
    ]
