# Generated by Django 4.2.6 on 2026-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_tenant_billing_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tenant_fill_enabled',
            field=models.BooleanField(default=False, verbose_name='允許租約租客補填'),
        ),
    ]
