# Generated by Django 4.2.6 on 2026-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_lease_fill_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', '待租客填寫'), ('submitted', '待管理者確認'), ('returned', '退回待租客填寫'), ('confirmed', '待租客付款'), ('payment_submitted', '待確認收款'), ('paid', '已結案'), ('void', '已作廢')], default='draft', max_length=24, verbose_name='帳單狀態'),
        ),
    ]
