# Generated by Django 4.2.6 on 2026-07-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_alter_bill_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-period', '-revision', '-created_at'], 'verbose_name': '帳單', 'verbose_name_plural': '帳單'},
        ),
        migrations.RemoveConstraint(
            model_name='bill',
            name='unique_bill_per_lease_period',
        ),
        migrations.AddField(
            model_name='bill',
            name='reissued_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacement_bills', to='rental.bill', verbose_name='重新建立來源帳單'),
        ),
        migrations.AddField(
            model_name='bill',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='帳單版次'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('lease', 'period', 'revision'), name='unique_bill_revision_per_lease_period'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'void'), _negated=True), fields=('lease', 'period'), name='unique_non_void_bill_per_lease_period'),
        ),
    ]
