# Generated by Django 4.2.6 on 2026-07-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='發生時間')),
                ('category', models.CharField(choices=[('authentication', '帳號驗證'), ('security', '安全事件'), ('system', '系統事件')], db_index=True, max_length=32, verbose_name='分類')),
                ('event_type', models.CharField(db_index=True, max_length=64, verbose_name='事件類型')),
                ('severity', models.CharField(choices=[('info', '資訊'), ('warning', '警告'), ('error', '錯誤'), ('critical', '嚴重')], db_index=True, default='info', max_length=16, verbose_name='嚴重度')),
                ('message', models.CharField(max_length=255, verbose_name='事件說明')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='來源 IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='請求路徑')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='請求方法')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='回應狀態碼')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='補充資料')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '系統日誌',
                'verbose_name_plural': '系統日誌',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'event_type', 'created_at'], name='auditlog_au_categor_1e9c01_idx'), models.Index(fields=['actor', 'created_at'], name='auditlog_au_actor_i_c7aafa_idx')],
            },
        ),
    ]
